In [ ]:
import numpy as np

docs= ['gp india',
       'india india',
       'hip hip hurray',
       'jeetega bhai jeetega india jeetega',
       'bharat mata ki jai',
       'kohli kohli',
       'sachin sachin',
       'dhoni dhoni',
       'dil ji ki jai',
       'inquilab zindabad'
]

In [ ]:
#oov_token will convert every new word with <nothing>
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token='<nothing>')

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

18

In [ ]:
tokenizer.word_counts

OrderedDict([('gp', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('dil', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [ ]:
tokenizer.word_docs

defaultdict(int,
            {'gp': 1,
             'india': 3,
             'hurray': 1,
             'hip': 1,
             'jeetega': 1,
             'bhai': 1,
             'mata': 1,
             'ki': 2,
             'bharat': 1,
             'jai': 2,
             'kohli': 1,
             'sachin': 1,
             'dhoni': 1,
             'dil': 1,
             'ji': 1,
             'inquilab': 1,
             'zindabad': 1})

In [ ]:
tokenizer.document_count

10

In [ ]:
#text_to_sequences ---> generate sequence
sequences= tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [ ]:
from keras.utils import pad_sequences

In [ ]:
#post means after --- zero will put after this
sequences =pad_sequences(sequences,padding='post')

In [ ]:
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [ ]:
from tensorflow.keras.layers import Embedding
model=Sequential()
model.add(Embedding(18,output_dim=2,input_length=5))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile('adam','accuracy')

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# The vocabulary size is len(tokenizer.word_index) + 1 to account for 0-based indexing and actual word indices
vocab_size = len(tokenizer.word_index) + 1

model = Sequential()
# Removed input_length as it is deprecated. Keras can infer the input shape.
model.add(Embedding(vocab_size, output_dim=2))
model.compile('adam', 'accuracy')

pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
[[[ 0.02506888  0.01005384]
  [ 0.04488114  0.01888483]
  [ 0.00216432 -0.01728178]
  [ 0.00216432 -0.01728178]
  [ 0.00216432 -0.01728178]]

 [[ 0.04488114  0.01888483]
  [ 0.04488114  0.01888483]
  [ 0.00216432 -0.01728178]
  [ 0.00216432 -0.01728178]
  [ 0.00216432 -0.01728178]]

 [[-0.00319856 -0.0101491 ]
  [-0.00319856 -0.0101491 ]
  [-0.02143407  0.03122324]
  [ 0.00216432 -0.01728178]
  [ 0.00216432 -0.01728178]]

 [[-0.01232924  0.04514613]
  [-0.01026804  0.01749057]
  [-0.01232924  0.04514613]
  [ 0.04488114  0.01888483]
  [-0.01232924  0.04514613]]

 [[ 0.0233028  -0.01475577]
  [ 0.01483799 -0.01975971]
  [-0.03357625 -0.00276665]
  [-0.03231319 -0.00379277]
  [ 0.00216432 -0.01728178]]

 [[ 0.02642256 -0.02023591]
  [ 0.02642256 -0.02023591]
  [ 0.00216432 -0.01728178]
  [ 0.00216432 -0.01728178]
  [ 0.00216432 -0.01728178]]

 [[ 0.01374936 -0.02722061]
  [ 0.01374936 -0.02722061]
  [ 0.00216432 -0.01728178]
  [ 0.00216432 -0.0172817

IMDB DATASET

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(x_train,y_train),(x_test,y_test)=imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
x_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [ ]:
x_train.shape

(25000,)

In [ ]:
x_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [ ]:
len(x_train[21]) #length of every text is not similar so we will cut the text

140

In [ ]:
#trim the text
#This give only first 50 words of every text
x_train=pad_sequences(x_train,padding='post',maxlen=50)
x_test=pad_sequences(x_test,padding='post',maxlen=50)

In [ ]:
x_train.shape

(25000, 50)

In [ ]:
#return sequences --->
model=Sequential()
model.add(Embedding(10000,2))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))